<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * basketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class basketRepository extends EntityRepository
{
}
